# Generated by Django 4.2.5 on 2023-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20231004_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Наличие балкона'),
        ),
    ]
