# Generated by Django 3.2 on 2023-10-04 11:28

from django.db import migrations
import phonenumbers


def update_owner_pure_phone_in_flat_table(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(pure_phone):
            flat.owner_pure_phone = pure_phone
            flat.save()


def clear_owner_pure_phone_in_flat_table(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20231004_1423'),
    ]

    operations = [
        migrations.RunPython(
            update_owner_pure_phone_in_flat_table, 
            clear_owner_pure_phone_in_flat_table
        )
    ]
