# Generated by Django 3.2 on 2023-10-04 12:11

from django.db import migrations


def copy_owners_from_flats(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(
                owner_name=flat.owner,
                phone=flat.owners_phonenumber,
                pure_phone=flat.owner_pure_phone
            )


def clear_owners(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.RunPython(
            copy_owners_from_flats, clear_owners
        )
    ]
