# Generated by Django 3.2 on 2023-10-04 13:13

from django.db import migrations


def copy_flats_to_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    flats = Flat.objects.all()
    for flat in flats.iterator():
        founded, created = Owner.objects.get_or_create(
            owner_name=flat.owner,
            phone=flat.owners_phonenumber
        )
        founded.owner_flats.add(flat)
        founded.save()


def clear_owner_flats(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner.owner_flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20231004_1511'),
    ]

    operations = [
        migrations.RunPython(
            copy_flats_to_owner, clear_owner_flats
        )
    ]
