# Generated by Django 3.2 on 2023-10-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_rename_owner_name_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_flats',
            new_name='flats',
        ),
    ]
