# Generated by Django 3.2 on 2023-10-05 05:22

from django.db import migrations


def change_new_building_in_flat_table(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__gt=2015).update(new_building=False)


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0019_alter_owner_flats"),
    ]

    operations = [
        migrations.RunPython(
            change_new_building_in_flat_table, migrations.RunPython.noop
        )
    ]
